
import 'dart:developer';
import 'package:flutter/material.dart';
import 'about.dart';
import 'splash_screen.dart';
import 'Azkar.dart';
import 'Counter.dart';
import 'Moshaf.dart';
import 'TextMoshaf.dart';
import 'hadith.dart';
import 'QesasAtfal.dart';
import 'Anbiaa.dart';
import 'Test.dart';
import 'haj.dart';
import 'ClassOne.dart';
void main() {
  runApp(Home());

}
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
      // TODO: implement build
      return MaterialApp(
          title: 'صديق المسلم',
          routes: {
              'home': (context) => ClassOne(),
              'Counter': (context) => Counter(),
              'Moshaf': (context) => Moshaf(),
              'Qesas': (context) => Qesas(),
              'about': (context) => about(),
              'TextMoshaf': (context) => TextMoshaf(),
              'Albaqra2': (context) => Albaqra2(),
              'Alemran3': (context) => Alemran3(),
              'Alnesaa': (context) => Alnesaa(),
              'Almaeda': (context) => Almaeda(),
              'Alanam': (context) => Alanam(),
              'Alaraf': (context) => Alaraf(),
              'Alanfal': (context) => Alanfal(),
              'Altawba': (context) => Altawba(),
              'Youns': (context) => Youns(),
              'Houd': (context) => Houd(),
              'Yosef': (context) => Yosef(),
              'Alrad': (context) => Alrad(),
              'Ibrahem': (context) => Ibrahem(),
              'Alhejr': (context) => Alhejr(),
              'Alnahl': (context) => Alnahl(),
              'Alesraa': (context) => Alesraa(),
              'Alkahf': (context) => Alkahf(),
              'Maream': (context) => Maream(),
              'Taha': (context) => Taha(),
              'Alanbia': (context) => Alanbia(),
              'Alhaj': (context) => Alhaj(),
              'Almomnon': (context) => Almomnon(),
              'Alnoor': (context) => Alnoor(),
              'Alforqan': (context) => Alforqan(),
              'Alshoraa': (context) => Alshoraa(),
              'Alnaml': (context) => Alnaml(),
              'Alqasas': (context) => Alqasas(),
              'Alankabot': (context) => Alankabot(),
              'Alroom': (context) => Alroom(),
              'Loqman': (context) => Loqman(),
              'Alsajda': (context) => Alsajda(),
              'Alahzab': (context) => Alahzab(),
              'Sabaa': (context) => Sabaa(),
              'Fater': (context) => Fater(),
              'Yasen': (context) => Yasen(),
              'Alsafat': (context) => Alsafat(),
              'Saad': (context) => Saad(),
              'Alzomar': (context) => Alzomar(),
              'Ghafer': (context) => Ghafer(),
              'Fosilat': (context) => Fosilat(),
              'Alshora': (context) => Alshora(),
              'Alzokhrof': (context) => Alzokhrof(),
              'Aldokhan': (context) => Aldokhan(),
              'Algathia': (context) => Algathia(),
              'Alahkaf': (context) => Alahkaf(),
              'Mohamed': (context) => Mohamed(),
              'Alfath': (context) => Alfath(),
              'Alhojrat': (context) => Alhojrat(),
              'Qaf': (context) => Qaf(),
              'Alzariat': (context) => Alzariat(),
              'Altoor': (context) => Altoor(),
              'Alnajm': (context) => Alnajm(),
              'Alqamar': (context) => Alqamar(),
              'Alrahman': (context) => Alrahman(),
              'Alwaqea': (context) => Alwaqea(),
              'Alhaded': (context) => Alhaded(),
              'Almojadla': (context) => Almojadla(),
              'Alhashr': (context) => Alhashr(),
              'Almomtahana': (context) => Almomtahana(),
              'Alsaf': (context) => Alsaf(),
              'Algomaa': (context) => Algomaa(),
              'Almonafkoon': (context) => Almonafkoon(),
              'Altaghabon': (context) => Altaghabon(),
              'Altalaq': (context) => Altalaq(),
              'Altahreem': (context) => Altahreem(),
              'Almolk': (context) => Almolk(),
              'Alqalam': (context) => Alqalam(),
              'Alhaqa': (context) => Alhaqa(),
              'Hadith2': (context) => Hadith2(),
              'Azkar': (context) => Azkar(),
              'Sabah': (context) => Sabah(),
              'Masaa': (context) => Masaa(),
              'Masjed': (context) => Masjed(),
              'Alsalah': (context) => Alsalah(),
              'Anbiaa': (context) => Anbiaa(),
              'Adam': (context) => Adam(),
              'Nouh': (context) => Nouh(),
              'Nouh': (context) => Nouh(),
              'Ibrahem2': (context) => Ibrahem2(),
              'Ismaeel': (context) => Ismaeel(),
              'Mousa': (context) => Mousa(),
              'Yousof': (context) => Yousof(),
              'Yaqob': (context) => Yaqob(),
              'Mohamed2': (context) => Mohamed2(),
              'Youns2': (context) => Youns2(),
              'Essa': (context) => Essa(),
              'Saleh': (context) => Saleh(),
              'Houd2': (context) => Houd2(),
              'Zakah': (context) => Zakah(),
              'haj': (context) => haj(),
              'hag2': (context) => hag2(),
              'hag3': (context) => hag3(),
              'Almaarej': (context) => Almaarej(),
              'Nouh2': (context) => Nouh2(),
              'Aljen': (context) => Aljen(),
              'Almozzamel': (context) => Almozzamel(),
              'Almoddather': (context) => Almoddather(),
              'Alqiama': (context) => Alqiama(),
              'Alinsan': (context) => Alinsan(),
              'Almorsalat': (context) => Almorsalat(),
              'Alnbaa': (context) => Alnbaa(),
              'Alnazeaat': (context) => Alnazeaat(),
              'Abs': (context) => Abs(),
              'Altakweer': (context) => Altakweer(),
              'Alenftar': (context) => Alenftar(),
              'Almtaffen': (context) => Almtaffen(),
              'Alensheqaq': (context) => Alensheqaq(),
              'Albrooj': (context) => Albrooj(),
              'Altareq': (context) => Altareq(),
              'Alaala': (context) => Alaala(),
              'Alghashia': (context) => Alghashia(),
              'Alfajr': (context) => Alfajr(),
              'Albalad': (context) => Albalad(),
              'Alshams': (context) => Alshams(),
              'Allil': (context) => Allil(),
              'Aldoha': (context) => Aldoha(),
              'Alsharh': (context) => Alsharh(),
              'Alteen': (context) => Alteen(),
              'Alalaq': (context) => Alalaq(),
              'Alqadr': (context) => Alqadr(),
              'Albaiena': (context) => Albaiena(),
              'Alzalzla': (context) => Alzalzla(),
              'Aladiat': (context) => Aladiat(),
              'Alqarea': (context) => Alqarea(),
              'Altkathor': (context) => Altkathor(),
              'Alasr': (context) => Alasr(),
              'Alhmaza': (context) => Alhmaza(),
              'Alfeel': (context) => Alfeel(),
              'Quriesh': (context) => Quriesh(),
              'Almaaon': (context) => Almaaon(),
              'Alkawther': (context) => Alkawther(),
              'Alkafroon': (context) => Alkafroon(),
              'Alnasr': (context) => Alnasr(),
              'Almasad': (context) => Almasad(),
              'Alsamad': (context) => Alsamad(),
              'Alfalaq': (context) => Alfalaq(),
              'Alnas': (context) => Alnas(),
              'Alnawm': (context) => Alnawm(),
              'Elyas': (context) => Elyas(),
              'yahia': (context) => yahia(),


          },
          debugShowCheckedModeBanner: false,
          home: SplashScreen()
      );
  }}
